// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "service.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message Void
 */
export interface Void {
}
/**
 * @generated from protobuf message Port
 */
export interface Port {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 2;
     */
    description: string;
    /**
     * @generated from protobuf field: BaseType type = 3;
     */
    type: BaseType;
}
/**
 * @generated from protobuf message Node
 */
export interface Node {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 2;
     */
    description: string;
    /**
     * @generated from protobuf field: string id = 3;
     */
    id: string;
    /**
     * @generated from protobuf field: repeated Port inputs = 4;
     */
    inputs: Port[];
    /**
     * @generated from protobuf field: repeated Port outputs = 5;
     */
    outputs: Port[];
}
/**
 * @generated from protobuf message Edge
 */
export interface Edge {
    /**
     * @generated from protobuf field: string from = 1;
     */
    from: string;
    /**
     * @generated from protobuf field: string to = 2;
     */
    to: string;
}
/**
 * @generated from protobuf message Capabilities
 */
export interface Capabilities {
    /**
     * @generated from protobuf field: repeated Node nodes = 1;
     */
    nodes: Node[];
}
/**
 * @generated from protobuf message GraphUpdated
 */
export interface GraphUpdated {
    /**
     * @generated from protobuf field: repeated Node nodes = 1;
     */
    nodes: Node[];
    /**
     * @generated from protobuf field: repeated Edge edges = 2;
     */
    edges: Edge[];
}
/**
 * @generated from protobuf enum BaseType
 */
export enum BaseType {
    /**
     * @generated from protobuf enum value: Int = 0;
     */
    Int = 0,
    /**
     * @generated from protobuf enum value: Float = 2;
     */
    Float = 2,
    /**
     * @generated from protobuf enum value: String = 3;
     */
    String = 3,
    /**
     * @generated from protobuf enum value: Color = 4;
     */
    Color = 4,
    /**
     * @generated from protobuf enum value: Curve = 5;
     */
    Curve = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class Void$Type extends MessageType<Void> {
    constructor() {
        super("Void", []);
    }
}
/**
 * @generated MessageType for protobuf message Void
 */
export const Void = new Void$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Port$Type extends MessageType<Port> {
    constructor() {
        super("Port", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "type", kind: "enum", T: () => ["BaseType", BaseType] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Port
 */
export const Port = new Port$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Node$Type extends MessageType<Node> {
    constructor() {
        super("Node", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "inputs", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Port },
            { no: 5, name: "outputs", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Port }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Node
 */
export const Node = new Node$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Edge$Type extends MessageType<Edge> {
    constructor() {
        super("Edge", [
            { no: 1, name: "from", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "to", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Edge
 */
export const Edge = new Edge$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Capabilities$Type extends MessageType<Capabilities> {
    constructor() {
        super("Capabilities", [
            { no: 1, name: "nodes", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Node }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Capabilities
 */
export const Capabilities = new Capabilities$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GraphUpdated$Type extends MessageType<GraphUpdated> {
    constructor() {
        super("GraphUpdated", [
            { no: 1, name: "nodes", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Node },
            { no: 2, name: "edges", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Edge }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GraphUpdated
 */
export const GraphUpdated = new GraphUpdated$Type();
/**
 * @generated ServiceType for protobuf service MyService
 */
export const MyService = new ServiceType("MyService", [
    { name: "GetCapabilities", options: {}, I: Void, O: Capabilities },
    { name: "NodesUpdated", options: {}, I: GraphUpdated, O: Void }
]);
